apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
  containers:
  - name: registry
    image: registry:2
    env:
    - name: REGISTRY_AUTH
      value: htpasswd
    - name: REGISTRY_AUTH_HTPASSWD_REALM
      value: "Registry Realm"
    - name: REGISTRY_AUTH_HTPASSWD_PATH
      value: /auth/htpasswd
    ports:
    - containerPort: 5000
      name: registry
    volumeMounts:
    - name: registry-storage
      mountPath: /var/lib/registry
    - name: auth
      mountPath: /auth
  volumes:
  - name: registry-storage
    emptyDir: {}
  - name: auth
    secret:
      secretName: registry-auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
  selector:
    app: registry